ruleDirs:
  - tools/ast-grep/rules-local
testConfigs:
  - testDir: tools/ast-grep/tests-local
customLanguages:
  zig:
    libraryPath: /Users/banteg/dev/tree-sitter-grammars/tree-sitter-zig/zig.dylib
    extensions: [zig]
    expandoChar: _
