// The native host runs snail-web.wasm, translated to C by wasm2c, as the
// browser page does: it implements the module's imports (WASI over the real
// file system, and the `snail` presenters on SDL3 GPU and SDL3_mixer) and
// drives its exports from SDL3 events.
#ifndef SNAIL_NATIVE_HOST_H
#define SNAIL_NATIVE_HOST_H

#include <stdint.h>

#include "game.h"  // generated by wasm2c

struct GpuPresenter;
struct MixerPresenter;

// Import module "snail": the presenters. `game` gives them linear memory.
struct w2c_snail {
    w2c_game* game;
    GpuPresenter* gpu;
    MixerPresenter* mixer;
};

struct WasiState;

// Import module "wasi_snapshot_preview1".
struct w2c_wasi__snapshot__preview1 {
    w2c_game* game;
    WasiState* state;
};

inline uint8_t* linear_memory(w2c_game* game) { return game->w2c_memory.data; }

// wasi.cpp: the file system root is `root`, the directory holding SnailMail.dat.
WasiState* wasi_create(const char* root);

// gpu.cpp
GpuPresenter* gpu_create(struct SDL_Window* window);
// Submit what the frame drew; `present` also scales it into the window.
void gpu_end_frame(GpuPresenter* gpu, bool present);
bool gpu_frame_pending(GpuPresenter* gpu);
bool gpu_save_frame(GpuPresenter* gpu, const char* path);  // the last 640x480 frame, as PNG

// mixer.cpp
MixerPresenter* mixer_create(bool muted);

#endif
