// Byte-sized runtime tile identities owned by cRSubLoc.
#ifndef SUB_LOC_TILE_IDS_H
#define SUB_LOC_TILE_IDS_H

// Keep the storage type separate from the value enum: VC6 gives ordinary
// enums four bytes, while cRSubLoc stores this owner in exactly one byte at
// +0x3c.
typedef unsigned char SubLocTileId;

enum SubLocTileIdValue {
    SUBLOC_TILE_EMPTY = 0x00,
    SUBLOC_TILE_FLOOR_DOT = 0x01,
    SUBLOC_TILE_RAMP_LEFT_BRACE = 0x02,
    SUBLOC_TILE_RAMP_GREATER = 0x03,
    SUBLOC_TILE_RAMP_RIGHT_BRACE = 0x04,
    SUBLOC_TILE_RAMP_LEFT_BRACKET = 0x05,
    SUBLOC_TILE_RAMP_LESS = 0x06,
    SUBLOC_TILE_RAMP_RIGHT_BRACKET = 0x07,
    SUBLOC_TILE_RAMP_LEFT_BRACE_RAISED = 0x08,
    SUBLOC_TILE_RAMP_GREATER_RAISED = 0x09,
    SUBLOC_TILE_RAMP_RIGHT_BRACE_RAISED = 0x0a,
    SUBLOC_TILE_RAMP_LEFT_BRACE_BACKPATCH = 0x0b,
    SUBLOC_TILE_RAMP_GREATER_BACKPATCH = 0x0c,
    SUBLOC_TILE_RAMP_RIGHT_BRACE_BACKPATCH = 0x0d,
    SUBLOC_TILE_WALL2 = 0x0e,
    SUBLOC_TILE_SLIDE_UNDERSCORE = 0x0f,
    SUBLOC_TILE_SLIDE_O = 0x10,
    SUBLOC_TILE_GLYPH_G = 0x11,
    SUBLOC_TILE_SLUG_HAZARD = 0x12,
    SUBLOC_TILE_SLIDE_F = 0x13,
    SUBLOC_TILE_FLOOR_VARIANT_14 = 0x14,
    SUBLOC_TILE_FLOOR_DASH = 0x15,
    SUBLOC_TILE_TRAMPOLINE = 0x16,
    SUBLOC_TILE_HEALTH_PICKUP = 0x17,
    SUBLOC_TILE_SPEEDUP_PICKUP = 0x18,
    SUBLOC_TILE_JETPACK_PICKUP = 0x19,
    SUBLOC_TILE_SLIDE_VARIANT_1A = 0x1a,
    SUBLOC_TILE_FLOOR_VARIANT_1B = 0x1b,
    SUBLOC_TILE_UNIVERSE_HOLE = 0x1c,
    SUBLOC_TILE_PATH_ENTRY_LOWERCASE = 0x1d,
    SUBLOC_TILE_PATH_ENTRY_UPPERCASE = 0x1e,
    SUBLOC_TILE_WIDE_VARIANT_1F = 0x1f,
    SUBLOC_TILE_FLOOR_HASH_MARKER = 0x20,
    SUBLOC_TILE_GARBAGE_HAZARD = 0x21,
    SUBLOC_TILE_SALT_HAZARD = 0x22,
    SUBLOC_TILE_RING_MARKER = 0x23,
};

#endif
